package be.doebi.aerismill.model.step.base;

import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

public enum StepEntityType {
    ADVANCED_BREP_SHAPE_REPRESENTATION("ADVANCED_BREP_SHAPE_REPRESENTATION"),
    ADVANCED_FACE("ADVANCED_FACE"),
    APPLICATION_CONTEXT("APPLICATION_CONTEXT"),
    APPLICATION_PROTOCOL_DEFINITION("APPLICATION_PROTOCOL_DEFINITION"),
    APPROVAL("APPROVAL"),
    APPROVAL_DATE_TIME("APPROVAL_DATE_TIME"),
    APPROVAL_PERSON_ORGANIZATION("APPROVAL_PERSON_ORGANIZATION"),
    APPROVAL_ROLE("APPROVAL_ROLE"),
    APPROVAL_STATUS("APPROVAL_STATUS"),
    AXIS1_PLACEMENT("AXIS1_PLACEMENT"),
    AXIS2_PLACEMENT_3D("AXIS2_PLACEMENT_3D"),
    BREP_WITH_VOIDS("BREP_WITH_VOIDS"),
    B_SPLINE_CURVE_WITH_KNOTS("B_SPLINE_CURVE_WITH_KNOTS"),
    B_SPLINE_SURFACE_WITH_KNOTS("B_SPLINE_SURFACE_WITH_KNOTS"),
    CALENDAR_DATE("CALENDAR_DATE"),
    CARTESIAN_POINT("CARTESIAN_POINT"),
    CIRCLE("CIRCLE"),
    CLOSED_SHELL("CLOSED_SHELL"),
    COLOUR_RGB("COLOUR_RGB"),
    COMPLEX_ENTITY("COMPLEX_ENTITY"),
    CONICAL_SURFACE("CONICAL_SURFACE"),
    CURVE_STYLE("CURVE_STYLE"),
    CYLINDRICAL_SURFACE("CYLINDRICAL_SURFACE"),
    DATE_AND_TIME("DATE_AND_TIME"),
    DATE_TIME_ROLE("DATE_TIME_ROLE"),
    DIRECTION("DIRECTION"),
    DOCUMENT("DOCUMENT"),
    DOCUMENT_TYPE("DOCUMENT_TYPE"),
    DRAUGHTING_PRE_DEFINED_COLOUR("DRAUGHTING_PRE_DEFINED_COLOUR"),
    DRAUGHTING_PRE_DEFINED_CURVE_FONT("DRAUGHTING_PRE_DEFINED_CURVE_FONT"),
    EDGE_CURVE("EDGE_CURVE"),
    EDGE_LOOP("EDGE_LOOP"),
    ELLIPSE("ELLIPSE"),
    FACE_BOUND("FACE_BOUND"),
    FACE_OUTER_BOUND("FACE_OUTER_BOUND"),
    FILL_AREA_STYLE("FILL_AREA_STYLE"),
    FILL_AREA_STYLE_COLOUR("FILL_AREA_STYLE_COLOUR"),
    GEOMETRIC_REPRESENTATION_CONTEXT("GEOMETRIC_REPRESENTATION_CONTEXT"),
    LINE("LINE"),
    LOCAL_TIME("LOCAL_TIME"),
    MANIFOLD_SOLID_BREP("MANIFOLD_SOLID_BREP"),
    MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION("MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION"),
    ORGANIZATION("ORGANIZATION"),
    ORIENTED_CLOSED_SHELL("ORIENTED_CLOSED_SHELL"),
    ORIENTED_EDGE("ORIENTED_EDGE"),
    OVER_RIDING_STYLED_ITEM("OVER_RIDING_STYLED_ITEM"),
    PERSON("PERSON"),
    PERSONAL_ADDRESS("PERSONAL_ADDRESS"),
    PERSON_AND_ORGANIZATION("PERSON_AND_ORGANIZATION"),
    PERSON_AND_ORGANIZATION_ROLE("PERSON_AND_ORGANIZATION_ROLE"),
    PLANE("PLANE"),
    PRESENTATION_LAYER_ASSIGNMENT("PRESENTATION_LAYER_ASSIGNMENT"),
    PRESENTATION_STYLE_ASSIGNMENT("PRESENTATION_STYLE_ASSIGNMENT"),
    PRODUCT_CATEGORY("PRODUCT_CATEGORY"),
    PRODUCT_CATEGORY_RELATIONSHIP("PRODUCT_CATEGORY_RELATIONSHIP"),
    PRODUCT_DEFINITION_SHAPE("PRODUCT_DEFINITION_SHAPE"),
    SECURITY_CLASSIFICATION("SECURITY_CLASSIFICATION"),
    SECURITY_CLASSIFICATION_LEVEL("SECURITY_CLASSIFICATION_LEVEL"),
    SHAPE_DEFINITION_REPRESENTATION("SHAPE_DEFINITION_REPRESENTATION"),
    SHAPE_REPRESENTATION("SHAPE_REPRESENTATION"),
    SPHERICAL_SURFACE("SPHERICAL_SURFACE"),
    STYLED_ITEM("STYLED_ITEM"),
    SURFACE_OF_REVOLUTION("SURFACE_OF_REVOLUTION"),
    SURFACE_SIDE_STYLE("SURFACE_SIDE_STYLE"),
    SURFACE_STYLE_FILL_AREA("SURFACE_STYLE_FILL_AREA"),
    SURFACE_STYLE_USAGE("SURFACE_STYLE_USAGE"),
    TOROIDAL_SURFACE("TOROIDAL_SURFACE"),
    VECTOR("VECTOR"),
    VERTEX_POINT("VERTEX_POINT");
    private final String name;

    StepEntityType(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    private static final Map<String, StepEntityType> BY_NAME =
            Arrays.stream(values())
                    .collect(Collectors.toUnmodifiableMap(
                            StepEntityType::getName,
                            Function.identity()
                    ));

    public static StepEntityType fromName(String name) {
        StepEntityType type = BY_NAME.get(name);
        if (type == null) {
            throw new IllegalArgumentException("Unknown STEP entity type: " + name);
        }
        return type;
    }

    public static StepEntityType fromNameOrNull(String name) {
        return BY_NAME.get(name);
    }

    public boolean matches(String rawTypeName) {
        return name.equals(rawTypeName);
    }

    @Override
    public String toString() {
        return name;
    }
}
